# apiVersion: v1
# kind: LimitRange
# metadata:
#   name: argo-limitrange-pod
#   namespace: argocd
# spec:
#   limits:
#   - type: Pod 
#     max:
#       memory: 2048Mi 
#       cpu: 2000m 
#     min:
#       memory: 128Mi 
#       cpu: 125m 
#     maxLimitRequestRatio:
#       memory: 1.5
#       cpu: 16

apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  limits:
  - default:
      cpu: 200m
      memory: 512Mi
    defaultRequest:
      cpu: 50m
      memory: 128Mi
    type: Container