apiVersion: v1
kind: ResourceQuota
metadata:
  name: ecommerce-quota
  namespace: ecommerce
spec:
  hard:
    requests.cpu: "3000m"
    requests.memory: 5Gi
    limits.cpu: "3500m"
    limits.memory: 12Gi

    

# ---
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: monitoring-quota
#   namespace: monitoring
# spec:
#   hard:
#     requests.cpu: "1"
#     requests.memory: 3Gi
#     limits.cpu: "2"
#     limits.memory: 6Gi
  

# ---
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: argocd-quota
#   namespace: argocd
# spec:
#   hard:
#     requests.cpu: "0.1"
#     requests.memory: 0.6Gi
#     limits.cpu: "0.3"
#     limits.memory: 1Gi
   
