apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pvc-volume
  namespace: 2mir-argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual

