apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: new-pvc-name
  namespace: namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual

